// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvofsmnkfiyawtwktjaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2b2ZzbW5rZml5YXd0d2t0amFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDE5MDgsImV4cCI6MjA3MTQxNzkwOH0.XO6KLZvyzHQ0bWJYa07zrV9M1lt6_wccD1Cky54t63Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});